apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rhny
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0045-tenant/tkrw-pr712-0075-0045-app/devfile-sample-rhny@sha256:584c87aef3ada0dc7f4957c11c4b8f614eeea917cf9fc34446e06bb2ce62d0fb
        name: my-nodejs
        resources: {}
status: {}
